#!/bin/bash

KS=weather
TABLE=temperature
DIR=/root/backup-$KS-$TABLE-20190927 # timestamped destination directory

AUTH='--username cassandra --password cassandra'
#AUTH='' # if no auth is used

one_node=10.135.221.62
all_nodes="10.135.221.62 10.135.220.14 10.135.220.10"

cqlsh $AUTH $one_node  -e "drop table ${KS}.$TABLE ;" 
echo table ${KS}.$TABLE is dropped. ENTER to continue
read tmp

echo creating the table ${KS}.$TABLE using $DIR/$one_node/$KS/$TABLE/schema.cql

cqlsh $AUTH $one_node <$DIR/$one_node/$KS/$TABLE/schema.cql
echo keyspace $KS is created. ENTER to continue
read tmp

for node in $all_nodes
do
    echo
    echo "node: $node"

    cd $DIR/$node/$KS
    
    t=$TABLE
        echo sstableloader $AUTH -d $one_node $DIR/$node/$KS/$t
             sstableloader $AUTH -d $one_node $DIR/$node/$KS/$t
done

