#!/bin/bash

KS=mydb1
DST_DIR=/root/backup-$KS-$(date +%Y%m%d) # timestamped destination directory

AUTH='--username cassandra --password cassandra'
#AUTH='' # if no auth is used

for node in c1 c2 c3 c4
do
    echo
    echo "node: $node"

    ssh -n $node nodetool $AUTH clearsnapshot $KS
    ssh -n $node nodetool $AUTH snapshot $KS


    TABLES=$( ssh -n $node "cd /var/lib/cassandra/data/$KS/ && ls" )
    for t in $TABLES
    do
        t=$( echo $t | cut -d- -f1 )

        mkdir -p $DST_DIR/$node/$KS/$t
        LAST_SNAPSHOT_DIR=$( ssh -n $node ls -dt /var/lib/cassandra/data/$KS/$t-*/snapshots/\[0-9\]\* | head -1 )

        echo scp $node:$LAST_SNAPSHOT_DIR/* $DST_DIR/$node/$KS/$t
             scp $node:$LAST_SNAPSHOT_DIR/* $DST_DIR/$node/$KS/$t

    done

done

# get the keyspace schema
cqlsh $AUTH c1 -e "describe keyspace $KS ;" > $DST_DIR/schema.cql


