#!/bin/bash

KS=weather
TABLE=temperature
DST_DIR=/root/backup-$KS-$TABLE-$(date +%Y%m%d) # timestamped destination directory

one_node=10.135.221.62
all_nodes="10.135.221.62 10.135.220.14 10.135.220.10"

AUTH='--username cassandra --password cassandra'
#AUTH='' # if no auth is used

for node in $all_nodes
do
    echo
    echo "node: $node"
    mkdir -p $DST_DIR/$node/$KS/$TABLE

    ssh -n $node nodetool $AUTH clearsnapshot $KS
    ssh -n $node nodetool $AUTH snapshot --table $TABLE $KS

    LAST_SNAPSHOT_DIR=''
    LAST_SNAPSHOT_DIR=$( ssh -n $node ls -dt /var/lib/cassandra/data/$KS/$TABLE-\*/snapshots/\[0-9\]\* | head -1 )
    [ "$LAST_SNAPSHOT_DIR" ] || continue

    echo scp $node:$LAST_SNAPSHOT_DIR/* $DST_DIR/$node/$KS/$TABLE
         scp $node:$LAST_SNAPSHOT_DIR/* $DST_DIR/$node/$KS/$TABLE
done

