#!/bin/bash

KS=weather
DST_DIR=/root/backup-$KS-$(date +%Y%m%d) # timestamped destination directory

AUTH='--username cassandra --password cassandra'
#AUTH='' # if no auth is used

one_node=10.135.221.62
all_nodes="10.135.221.62 10.135.220.14 10.135.220.10"

for node in $all_nodes
do
    echo
    echo "node: $node"

    ssh -n $node nodetool $AUTH clearsnapshot $KS
    ssh -n $node nodetool $AUTH snapshot $KS


    TABLES=$( ssh -n $node "cd /var/lib/cassandra/data/$KS/ && ls" )
    for t in $TABLES
    do
        t=$( echo $t | cut -d- -f1 )

        mkdir -p $DST_DIR/$node/$KS/$t
        LAST_SNAPSHOT_DIR=$( ssh -n $node ls -dt /var/lib/cassandra/data/$KS/$t-*/snapshots/\[0-9\]\* | head -1 )

        echo scp $node:$LAST_SNAPSHOT_DIR/* $DST_DIR/$node/$KS/$t
             scp $node:$LAST_SNAPSHOT_DIR/* $DST_DIR/$node/$KS/$t

    done

done

# get the keyspace schema
cqlsh $AUTH $one_node -e "describe keyspace $KS ;" > $DST_DIR/schema.cql


